const CREATE_ORDER = 'CREATE_ORDER';
const MOVE_ORDER_TO_FARM = 'MOVE_ORDER_TO_FARM';
const MOVE_ORDER_TO_CUSTOMER = 'MOVE_ORDER_TO_CUSTOMER';

export default {
	CREATE_ORDER,
	MOVE_ORDER_TO_FARM,
	MOVE_ORDER_TO_CUSTOMER,
}